name: Docker Publish (Production Images)

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - src/**
      - .github/workflows/**
      - github-cli-build-version.txt

jobs:
  build-test-images:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    secrets: inherit
    with:
      release_type: 'latest'
      push: false